

#X = 10

try:
    print(X)
except:
    print("hubo un error")
